namespace FSharp.Finance.Personal

open Scheduling
open Quotes

/// functions for refinancing payments after an original schedule failed to amortise
module Refinancing =

    open Amortisation
    open Calculation
    open DateDay
    open UnitPeriod

    /// the parameters used for setting up additional items for an existing schedule or new items for a new schedule
    [<RequireQualifiedAccess>]
    type RescheduleParameters = {
        /// whether the fee should be pro-rated or due in full in the new schedule
        FeeSettlementRebate: Fee.SettlementRebate
        /// whether the plan is autogenerated or a manual plan provided
        PaymentSchedule: ScheduleConfig
        /// how to handle interest on negative principal balances
        RateOnNegativeBalance: Interest.Rate
        /// any promotional or introductory offers during which a different interest rate is applicable
        PromotionalInterestRates: Interest.PromotionalRate array
        /// whether and when to generate a settlement figure, otherwise just a statement will be generated
        SettlementDay: SettlementDay
    }

    /// the parameters used for setting up additional items for an existing schedule or new items for a new schedule
    module RescheduleParameters =

        /// formats the parameters items as an HTML table
        let toHtmlTable (rp: RescheduleParameters) =
            $"""
<table>
    <thead><tr><th colspan="2">Reschedule Parameters</th></tr></thead>
    <tr><td>Fee Settlement Rebate</td><td>{rp.FeeSettlementRebate}</td></tr>
    <tr><td>Payment Schedule</td><td>{ScheduleConfig.toHtmlTable rp.PaymentSchedule}</td></tr>
    <tr><td>Rate on Negative Balance</td><td>{rp.RateOnNegativeBalance}</td></tr>
    <tr><td>Promotional Interest Rates</td><td>{Array.toStringOrNa rp.PromotionalInterestRates}</td></tr>
    <tr><td>Settlement Day</td><td>{rp.SettlementDay}</td></tr>
</table>"""

    /// merges scheduled payments, determining the currently valid original and rescheduled payments, and preserving a record of any previous payments that have been superseded
    let mergeScheduledPayments (scheduledPayments: (int<OffsetDay> * ScheduledPayment) array) =
        // get a sorted array of all days on which payments are rescheduled
        let rescheduleDays =
            scheduledPayments
            |> Array.map snd
            |> Array.choose (fun sp ->
                if sp.Rescheduled.IsSome then
                    Some sp.Rescheduled.Value.RescheduleDay
                else
                    None
            )
            |> Array.distinct
            |> Array.sort
        // return the list of scheduled payments with the original and rescheduled payments merged
        scheduledPayments
        //group and sort by day
        |> Array.groupBy fst
        |> Array.sortBy fst
        |> Array.mapFold
            (fun previousRescheduleDay (offsetDay, map) ->
                // evaluate the scheduled payment
                let scheduledPayments = map |> Array.map snd
                // get any original payment due on the day
                let original = scheduledPayments |> Array.tryFind _.Original.IsSome |> toValueOption
                // get any rescheduled payments due on the day, ordering them so that the most recently rescheduled payments come first
                let rescheduled =
                    scheduledPayments
                    |> Array.filter _.Rescheduled.IsSome
                    |> Array.sortByDescending _.Rescheduled.Value.RescheduleDay
                    |> Array.toList
                // split any rescheduled payments into latest and previous
                let latestRescheduling, previousReschedulings =
                    match rescheduled with
                    | [ r ] -> ValueSome r, []
                    | r :: pr -> ValueSome r, pr
                    | _ -> ValueNone, []
                // update the previous reschedule day, if any
                let newRescheduleDay =
                    rescheduleDays
                    |> Array.tryFind (fun d -> offsetDay >= d)
                    |> toValueOption
                    |> ValueOption.orElse previousRescheduleDay
                // create the modified scheduled payment
                let newScheduledPayment =
                    match original, latestRescheduling with
                    // if there are any rescheduled payments, add the latest as well as the list of previously rescheduled payments on the day (also include the original if any on the day)
                    | _, ValueSome r ->
                        Some(
                            offsetDay,
                            {
                                Original = original |> ValueOption.bind _.Original
                                Rescheduled = r.Rescheduled
                                PreviousRescheduled =
                                    previousReschedulings
                                    |> List.rev
                                    |> List.map _.Rescheduled.Value
                                    |> List.toArray
                                Adjustment = r.Adjustment
                                Metadata = r.Metadata
                            }
                        )
                    // if there is no rescheduled payment on the day, but just an original payment, include the original payment as-is
                    // note: if the original payment day is preceded by any rescheduling, then assume that this cancels the original payment, so enter this as a zero-valued rescheduled payment on the day
                    | ValueSome o, ValueNone ->
                        Some(
                            offsetDay,
                            {
                                Original = o.Original
                                Rescheduled =
                                    newRescheduleDay
                                    |> ValueOption.bind (fun nrd ->
                                        if offsetDay >= nrd then
                                            //overwrite original scheduled payments from start of rescheduled payments
                                            ValueSome {
                                                Value = 0L<Cent>
                                                RescheduleDay = nrd
                                            }
                                        else
                                            ValueNone
                                    )
                                PreviousRescheduled = [||]
                                Adjustment = o.Adjustment
                                Metadata = o.Metadata
                            }
                        )
                    // if there are no original or rescheduled payments, ignore
                    | ValueNone, ValueNone -> None

                newScheduledPayment, newRescheduleDay
            )
            ValueNone
        |> fst
        |> Array.choose id
        // convert the result to a map
        |> Map.ofArray

    /// take an existing schedule and reschedule the remaining payments e.g. to allow the customer more time to pay
    let reschedule p (rp: RescheduleParameters) actualPayments =

        // get the settlement quote
        let quote = getQuote p actualPayments

        // create a new payment schedule either by auto-generating it or using manual payments
        let newPaymentSchedule =
            match rp.PaymentSchedule with
            | AutoGenerateSchedule _ ->
                calculateBasicSchedule {
                    p.Basic with
                        ScheduleConfig = rp.PaymentSchedule
                }
                |> _.Items
                |> Array.filter (_.ScheduledPayment >> ScheduledPayment.isSome)
                |> Array.map (fun si -> si.Day, si.ScheduledPayment)
            | FixedSchedules fixedSchedules ->
                fixedSchedules
                |> Array.collect (fun fs ->
                    let scheduledPayment =
                        match fs.ScheduleType with
                        | ScheduleType.Original -> ScheduledPayment.quick (ValueSome fs.PaymentValue) ValueNone
                        | ScheduleType.Rescheduled rescheduleDay ->
                            ScheduledPayment.quick
                                ValueNone
                                (ValueSome {
                                    Value = fs.PaymentValue
                                    RescheduleDay = rescheduleDay
                                })

                    UnitPeriod.generatePaymentSchedule
                        (UnitPeriod.PaymentCount fs.PaymentCount)
                        UnitPeriod.Direction.Forward
                        fs.UnitPeriodConfig
                    |> Array.map (fun d -> OffsetDay.fromDate p.Basic.StartDate d, scheduledPayment)
                )
            | CustomSchedule payments -> payments |> Map.toArray

        // append the new schedule to the old schedule up to the point of settlement
        let oldPaymentSchedule =
            quote.Schedules.AmortisationSchedule.ScheduleItems
            |> Map.filter (fun _ si -> ScheduledPayment.isSome si.ScheduledPayment)
            |> Map.map (fun _ si -> si.ScheduledPayment)
            |> Map.toArray

        // configure the parameters for the new schedule
        let pNew = {
            p with
                Basic.ScheduleConfig =
                    [| oldPaymentSchedule; newPaymentSchedule |]
                    |> Array.concat
                    |> mergeScheduledPayments
                    |> CustomSchedule
                Advanced.FeeConfig =
                    p.Advanced.FeeConfig
                    |> ValueOption.map (fun fc -> {
                        fc with
                            SettlementRebate = rp.FeeSettlementRebate
                    })
                Advanced.InterestConfig.InitialGracePeriod = 0<DurationDay>
                Advanced.InterestConfig.PromotionalRates = rp.PromotionalInterestRates
                Advanced.InterestConfig.RateOnNegativeBalance = rp.RateOnNegativeBalance
                Advanced.SettlementDay = rp.SettlementDay
                Advanced.TrimEnd = true
        }

        // create the new amortisation schedule
        let rescheduledSchedules = amortise pNew actualPayments

        // return the results
        {|
            OldSchedules = quote.Schedules
            NewSchedules = rescheduledSchedules
        |}

    /// parameters for creating a rolled-over schedule
    [<RequireQualifiedAccess>]
    type RolloverParameters = {
        /// the final payment day of the original schedule
        OriginalFinalPaymentDay: int<OffsetDay>
        /// the scheduled payments or the parameters for generating them
        PaymentSchedule: ScheduleConfig
        /// options relating to interest
        InterestConfig: Interest.BasicConfig
        /// options relating to payment
        PaymentConfig: Payment.BasicConfig
        /// how to handle any outstanding fee balance
        FeeHandling: Fee.FeeHandling
    }

    /// parameters for creating a rolled-over schedule
    module RolloverParameters =

        /// formats the parameters items as an HTML table
        let toHtmlTable (rp: RolloverParameters) =
            $"""
<table>
    <thead><tr><th colspan="2">Rollover Parameters</th></tr></thead>
    <tr><td>Original Final Payment Day</td><td>{rp.OriginalFinalPaymentDay}</td></tr>
    <tr><td>Payment Schedule</td><td>{ScheduleConfig.toHtmlTable rp.PaymentSchedule}</td></tr>
    <tr><td>Interest Config</td><td>{rp.InterestConfig}</td></tr>
    <tr><td>Payment Config</td><td>{rp.PaymentConfig}</td></tr>
    <tr><td>Fee Handling</td><td>{rp.FeeHandling}</td></tr>
</table>"""

    /// take an existing schedule and settle it, then use the result to create a new schedule to pay it off under different terms
    let rollOver p (rp: RolloverParameters) actualPayments =

        // get the settlement quote
        let quote = getQuote p actualPayments

        // process the quote and extract the portions if applicable
        let principalPortion, feePortion, feeRebateIfSettled =
            match quote.QuoteResult with
            | PaymentQuote({ Apportionment = a } as pq) ->
                match rp.FeeHandling with
                | Fee.FeeHandling.CapitaliseAsPrincipal ->
                    a.PrincipalPortion + a.FeePortion + a.InterestPortion + a.ChargesPortion,
                    0L<Cent>,
                    pq.FeeRebateIfSettled
                | Fee.FeeHandling.CarryOverAsIs ->
                    a.PrincipalPortion + a.InterestPortion + a.ChargesPortion, a.FeePortion, pq.FeeRebateIfSettled
                | Fee.FeeHandling.WriteOffFeeBalance ->
                    a.PrincipalPortion + a.InterestPortion + a.ChargesPortion, a.FeePortion, pq.FeeRebateIfSettled
            | _ -> failwith "Unable to obtain quote for rollover"

        // configure the parameters for the new schedule
        let pNew = {
            p with
                Basic.StartDate = p.Basic.EvaluationDate
                Basic.Principal = principalPortion
                Basic.ScheduleConfig = rp.PaymentSchedule
                Basic.InterestConfig = rp.InterestConfig
                Basic.PaymentConfig = rp.PaymentConfig
                Basic.FeeConfig =
                    p.Basic.FeeConfig
                    |> ValueOption.bind (fun fc ->
                        match rp.FeeHandling with
                        | Fee.FeeHandling.CarryOverAsIs ->
                            {
                                fc with
                                    FeeType = Fee.CustomFee("Rollover Fee", Amount.Simple feePortion)
                            }
                            |> ValueSome
                        | _ -> ValueNone
                    )
                Advanced.FeeConfig =
                    p.Advanced.FeeConfig
                    |> ValueOption.map (fun fc -> {
                        fc with
                            SettlementRebate =
                                if feeRebateIfSettled = 0L<Cent> then
                                    Fee.SettlementRebate.Zero
                                else
                                    match fc.SettlementRebate with
                                    | Fee.SettlementRebate.ProRata
                                    | Fee.SettlementRebate.ProRataRescheduled _ ->
                                        Fee.SettlementRebate.ProRataRescheduled rp.OriginalFinalPaymentDay
                                    | _ as fsr -> fsr
                    })
                Advanced.SettlementDay = SettlementDay.NoSettlement
                Advanced.TrimEnd = true
        }

        // create the new amortisation schedule
        let rolledOverSchedules = amortise pNew Map.empty

        // return the results
        {|
            OldSchedules = quote.Schedules
            NewSchedules = rolledOverSchedules
        |}

    /// given a unit-period config and a new start date, produce a new unit-period config with the same unit period type
    let private unitPeriodConfigFromDate (startDate: Date) (unitPeriodConfig: Config) =
        unitPeriodConfig |> Config.unitPeriod |> Config.from startDate

    /// how to handle interest that accrues during a payment holiday
    [<RequireQualifiedAccess; Struct; StructuredFormatDisplay("{Html}")>]
    type DeferredInterestHandling =
        /// add the accrued holiday interest to the outstanding balance and recalculate payments for the remaining term
        | CapitaliseAsNewPrincipal
        /// distribute the accrued holiday interest evenly over the remaining scheduled payments
        | SpreadOverRemainingTerm

        member x.Html =
            match x with
            | CapitaliseAsNewPrincipal -> "capitalise as new principal"
            | SpreadOverRemainingTerm -> "spread over remaining term"

    /// parameters for applying a scheduled payment holiday to an existing loan
    [<RequireQualifiedAccess>]
    type PaymentHolidayParameters = {
        /// the first day of the payment holiday (inclusive), expressed as an offset from the loan start date
        HolidayStartDay: int<OffsetDay>
        /// the last day of the payment holiday (inclusive), expressed as an offset from the loan start date
        HolidayEndDay: int<OffsetDay>
        /// how to handle interest that accrues during the holiday period
        InterestHandling: DeferredInterestHandling
        /// whether and when to generate a settlement figure on the new schedule
        SettlementDay: SettlementDay
    }

    /// how an overpayment is applied to the remaining schedule
    [<RequireQualifiedAccess; Struct; StructuredFormatDisplay("{Html}")>]
    type OverpaymentHandling =
        /// keep the scheduled payment amount the same and shorten the term
        | ReduceTerm
        /// keep the same number of remaining payments and recalculate a lower payment amount
        | ReducePayment

        member x.Html =
            match x with
            | ReduceTerm -> "reduce term"
            | ReducePayment -> "reduce payment"

    /// parameters for applying an overpayment to an existing schedule
    [<RequireQualifiedAccess>]
    type OverpaymentParameters = {
        /// how the overpayment should be applied to the remaining schedule
        OverpaymentHandling: OverpaymentHandling
        /// whether and when to generate a settlement figure on the new schedule
        SettlementDay: SettlementDay
    }

    /// apply a scheduled payment holiday to an existing loan, modelling the impact on outstanding balance, term, and total interest;
    /// the holiday period payments are deferred to zero and the subsequent schedule is adjusted according to the chosen interest handling
    let paymentHoliday (p: Parameters) (php: PaymentHolidayParameters) actualPayments =

        // get the original basic schedule
        let basicSchedule = calculateBasicSchedule p.Basic

        // extract all payment items from the basic schedule
        let allPaymentItems =
            basicSchedule.Items
            |> Array.filter (_.ScheduledPayment >> ScheduledPayment.isSome)

        // partition into pre-holiday, holiday, and post-holiday items
        let preHolidayItems =
            allPaymentItems |> Array.filter (fun bi -> bi.Day < php.HolidayStartDay)

        let holidayItems =
            allPaymentItems
            |> Array.filter (fun bi -> bi.Day >= php.HolidayStartDay && bi.Day <= php.HolidayEndDay)

        let postHolidayItems =
            allPaymentItems |> Array.filter (fun bi -> bi.Day > php.HolidayEndDay)

        // pre-holiday payments are kept as-is
        let preHolidayPaymentMap =
            preHolidayItems |> Array.map (fun bi -> bi.Day, bi.ScheduledPayment)

        // create zero-valued rescheduled payments for the holiday period
        let holidayPaymentMap =
            holidayItems
            |> Array.map (fun bi ->
                bi.Day,
                {
                    bi.ScheduledPayment with
                        Rescheduled =
                            ValueSome {
                                Value = 0L<Cent>
                                RescheduleDay = php.HolidayStartDay
                            }
                }
            )

        // simulate the schedule with zero holiday payments to determine the balance at the end of the holiday
        let getHolidayEndScheduleItem () =
            let tempScheduleConfig =
                [| preHolidayPaymentMap; holidayPaymentMap |]
                |> Array.concat
                |> Map.ofArray
                |> CustomSchedule

            let tempParams = {
                p with
                    Basic.ScheduleConfig = tempScheduleConfig
                    Basic.EvaluationDate = p.Basic.StartDate.AddDays(int php.HolidayEndDay)
                    Advanced.SettlementDay = SettlementDay.NoSettlement
                    Advanced.TrimEnd = false
            }

            amortise tempParams actualPayments
            |> fun result ->
                result.AmortisationSchedule.ScheduleItems
                |> Map.toArray
                |> Array.filter (fun (d, _) -> d <= php.HolidayEndDay)
                |> Array.tryLast
                |> Option.map snd

        // derive the unit-period config for the post-holiday schedule, anchored to the given start date
        let postHolidayUnitPeriodConfig (startDate: Date) =
            match p.Basic.ScheduleConfig with
            | AutoGenerateSchedule ags -> unitPeriodConfigFromDate startDate ags.UnitPeriodConfig
            | _ -> Config.defaultMonthly 1 startDate

        // calculate the post-holiday payment map based on the chosen interest handling method
        let postHolidayPaymentMap =
            if Array.isEmpty postHolidayItems || Array.isEmpty holidayItems then
                // no payments were scheduled during the holiday window: nothing to capitalise or spread
                postHolidayItems |> Array.map (fun bi -> bi.Day, bi.ScheduledPayment)
            else
                let remainingCount = Array.length postHolidayItems

                match php.InterestHandling with

                | DeferredInterestHandling.CapitaliseAsNewPrincipal ->
                    // simulate to get the balance at the end of the holiday
                    match getHolidayEndScheduleItem () with
                    | None -> postHolidayItems |> Array.map (fun bi -> bi.Day, bi.ScheduledPayment)
                    | Some si ->
                        // capitalise outstanding principal and accrued interest into a new principal
                        let capitalised =
                            si.PrincipalBalance
                            + Cent.fromDecimalCent p.Basic.InterestConfig.Rounding si.InterestBalance

                        if capitalised <= 0L<Cent> then
                            postHolidayItems |> Array.map (fun bi -> bi.Day, bi.ScheduledPayment)
                        else
                            let holidayEndDate = p.Basic.StartDate.AddDays(int php.HolidayEndDay)
                            let firstPostHolidayDate =
                                postHolidayItems |> Array.head |> _.Day |> OffsetDay.toDate p.Basic.StartDate

                            // generate a new schedule from the capitalised balance to determine the new payment amounts
                            let newBasicParams = {
                                p.Basic with
                                    StartDate = holidayEndDate
                                    EvaluationDate = holidayEndDate
                                    Principal = capitalised
                                    FeeConfig = ValueNone
                                    ScheduleConfig =
                                        AutoGenerateSchedule {
                                            UnitPeriodConfig =
                                                postHolidayUnitPeriodConfig firstPostHolidayDate
                                            ScheduleLength = PaymentCount remainingCount
                                        }
                            }

                            let newBasicSchedule = calculateBasicSchedule newBasicParams

                            let newPaymentValues =
                                newBasicSchedule.Items
                                |> Array.filter (_.ScheduledPayment >> ScheduledPayment.isSome)
                                |> Array.map (fun bi -> ScheduledPayment.total bi.ScheduledPayment)

                            // map new payment values to the original post-holiday offset days
                            let safeLength = min (Array.length postHolidayItems) (Array.length newPaymentValues)

                            postHolidayItems.[..safeLength - 1]
                            |> Array.mapi (fun i bi ->
                                bi.Day,
                                {
                                    bi.ScheduledPayment with
                                        Rescheduled =
                                            ValueSome {
                                                Value = newPaymentValues.[i]
                                                RescheduleDay = php.HolidayStartDay
                                            }
                                }
                            )

                | DeferredInterestHandling.SpreadOverRemainingTerm ->
                    // simulate to get the capitalised balance at the end of the holiday
                    match getHolidayEndScheduleItem () with
                    | None -> postHolidayItems |> Array.map (fun bi -> bi.Day, bi.ScheduledPayment)
                    | Some si ->
                        let capitalised =
                            si.PrincipalBalance
                            + Cent.fromDecimalCent p.Basic.InterestConfig.Rounding si.InterestBalance

                        if capitalised <= 0L<Cent> then
                            postHolidayItems |> Array.map (fun bi -> bi.Day, bi.ScheduledPayment)
                        else
                            let holidayEndDate = p.Basic.StartDate.AddDays(int php.HolidayEndDay)
                            let firstPostHolidayDate =
                                postHolidayItems |> Array.head |> _.Day |> OffsetDay.toDate p.Basic.StartDate

                            // calculate the new level payment needed to clear the capitalised balance
                            // over the remaining count (same calculation as CapitaliseAsNewPrincipal)
                            let newBasicParams = {
                                p.Basic with
                                    StartDate = holidayEndDate
                                    EvaluationDate = holidayEndDate
                                    Principal = capitalised
                                    FeeConfig = ValueNone
                                    ScheduleConfig =
                                        AutoGenerateSchedule {
                                            UnitPeriodConfig =
                                                postHolidayUnitPeriodConfig firstPostHolidayDate
                                            ScheduleLength = PaymentCount remainingCount
                                        }
                            }

                            let newBasicSchedule = calculateBasicSchedule newBasicParams

                            let newPaymentValues =
                                newBasicSchedule.Items
                                |> Array.filter (_.ScheduledPayment >> ScheduledPayment.isSome)
                                |> Array.map (fun bi -> ScheduledPayment.total bi.ScheduledPayment)

                            // the extra per payment is the difference between the new and original level payments;
                            // distribute it evenly, adding any rounding remainder to the last payment
                            let originalLevelPayment =
                                postHolidayItems
                                |> Array.head
                                |> fun bi -> ScheduledPayment.total bi.ScheduledPayment

                            let safeLength = min (Array.length postHolidayItems) (Array.length newPaymentValues)

                            postHolidayItems.[..safeLength - 1]
                            |> Array.mapi (fun i bi ->
                                let extra = newPaymentValues.[i] - originalLevelPayment

                                bi.Day,
                                {
                                    bi.ScheduledPayment with
                                        Rescheduled =
                                            ValueSome {
                                                Value = ScheduledPayment.total bi.ScheduledPayment + (max 0L<Cent> extra)
                                                RescheduleDay = php.HolidayStartDay
                                            }
                                }
                            )

        // merge all payment maps into a single custom schedule
        let newScheduleConfig =
            [| preHolidayPaymentMap; holidayPaymentMap; postHolidayPaymentMap |]
            |> Array.concat
            |> mergeScheduledPayments
            |> CustomSchedule

        // configure the new parameters
        let pNew = {
            p with
                Basic.ScheduleConfig = newScheduleConfig
                Advanced.InterestConfig.InitialGracePeriod = 0<DurationDay>
                Advanced.SettlementDay = php.SettlementDay
                Advanced.TrimEnd = true
        }

        // generate and return both the old and new schedules
        let oldSchedules = amortise p actualPayments
        let newSchedules = amortise pNew actualPayments

        {|
            OldSchedules = oldSchedules
            NewSchedules = newSchedules
        |}

    /// apply an overpayment to an existing schedule, modelling the effect on either term length or payment amount;
    /// the overpayment must already be included in actualPayments and the evaluation date must reflect when the overpayment was made
    let applyOverpayment (p: Parameters) (op: OverpaymentParameters) actualPayments =

        // get the original basic schedule
        let basicSchedule = calculateBasicSchedule p.Basic

        // get the settlement quote at the evaluation date (accounts for all actual payments including the overpayment)
        let quote = getQuote p actualPayments

        // get the outstanding principal balance after the overpayment
        let outstandingPrincipal =
            match quote.QuoteResult with
            | PaymentQuote pq -> pq.Apportionment.PrincipalPortion
            | _ -> 0L<Cent>

        // get the evaluation day offset
        let evaluationDay = OffsetDay.fromDate p.Basic.StartDate p.Basic.EvaluationDate

        // get remaining payment items from the original schedule (those after the evaluation date)
        let remainingItems =
            basicSchedule.Items
            |> Array.filter (fun bi -> bi.Day > evaluationDay && ScheduledPayment.isSome bi.ScheduledPayment)

        // get the original payment schedule up to the evaluation date from the quote schedules
        let oldPaymentSchedule =
            quote.Schedules.AmortisationSchedule.ScheduleItems
            |> Map.filter (fun _ si -> ScheduledPayment.isSome si.ScheduledPayment)
            |> Map.map (fun _ si -> si.ScheduledPayment)
            |> Map.toArray

        // get the original level payment
        let levelPayment = basicSchedule.Stats.LevelPayment

        // create the new payment schedule based on the chosen overpayment handling
        let newPaymentSchedule =
            if Array.isEmpty remainingItems then
                [||]
            else
                let remainingCount = Array.length remainingItems

                match op.OverpaymentHandling with

                | OverpaymentHandling.ReduceTerm ->
                    // keep the same payment amount; the reduced balance means the loan pays off sooner
                    remainingItems
                    |> Array.map (fun bi ->
                        bi.Day,
                        {
                            bi.ScheduledPayment with
                                Rescheduled =
                                    ValueSome {
                                        Value = levelPayment
                                        RescheduleDay = evaluationDay
                                    }
                        }
                    )

                | OverpaymentHandling.ReducePayment ->
                    // calculate a lower payment amount based on the outstanding balance and the remaining payment count;
                    // StartDate is the evaluation date (so interest accrues from that date), while the
                    // unit-period config is anchored to the first remaining payment date so that the generated
                    // payment schedule matches the original post-overpayment payment days exactly
                    let firstRemainingDate =
                        remainingItems |> Array.head |> _.Day |> OffsetDay.toDate p.Basic.StartDate

                    let newBasicParams = {
                        p.Basic with
                            StartDate = p.Basic.EvaluationDate
                            EvaluationDate = p.Basic.EvaluationDate
                            Principal = outstandingPrincipal
                            FeeConfig = ValueNone
                            ScheduleConfig =
                                AutoGenerateSchedule {
                                    UnitPeriodConfig =
                                        match p.Basic.ScheduleConfig with
                                        | AutoGenerateSchedule ags -> unitPeriodConfigFromDate firstRemainingDate ags.UnitPeriodConfig
                                        | _ -> Config.defaultMonthly 1 firstRemainingDate
                                    ScheduleLength = PaymentCount remainingCount
                                }
                    }

                    let newLevelPayment = (calculateBasicSchedule newBasicParams).Stats.LevelPayment

                    remainingItems
                    |> Array.map (fun bi ->
                        bi.Day,
                        {
                            bi.ScheduledPayment with
                                Rescheduled =
                                    ValueSome {
                                        Value = newLevelPayment
                                        RescheduleDay = evaluationDay
                                    }
                        }
                    )

        // merge old and new payment schedules
        let mergedScheduleConfig =
            [| oldPaymentSchedule; newPaymentSchedule |]
            |> Array.concat
            |> mergeScheduledPayments
            |> CustomSchedule

        // configure the new parameters
        let pNew = {
            p with
                Basic.ScheduleConfig = mergedScheduleConfig
                Advanced.InterestConfig.InitialGracePeriod = 0<DurationDay>
                Advanced.SettlementDay = op.SettlementDay
                Advanced.TrimEnd = true
        }

        // generate and return both the old and new schedules
        let newSchedules = amortise pNew actualPayments

        {|
            OldSchedules = quote.Schedules
            NewSchedules = newSchedules
        |}
