namespace FSharp.Finance.Personal

open System
open Scheduling
open Quotes

/// functions for refinancing payments after an original schedule failed to amortise
module Refinancing =

    open Amortisation
    open Calculation
    open DateDay

    /// the parameters used for setting up additional items for an existing schedule or new items for a new schedule
    [<RequireQualifiedAccess>]
    type RescheduleParameters = {
        /// whether the fee should be pro-rated or due in full in the new schedule
        FeeSettlementRebate: Fee.SettlementRebate
        /// whether the plan is autogenerated or a manual plan provided
        PaymentSchedule: ScheduleConfig
        /// how to handle interest on negative principal balances
        RateOnNegativeBalance: Interest.Rate
        /// any promotional or introductory offers during which a different interest rate is applicable
        PromotionalInterestRates: Interest.PromotionalRate array
        /// whether and when to generate a settlement figure, otherwise just a statement will be generated
        SettlementDay: SettlementDay
    }

    /// the parameters used for setting up additional items for an existing schedule or new items for a new schedule
    module RescheduleParameters =

        /// formats the parameters items as an HTML table
        let toHtmlTable (rp: RescheduleParameters) =
            $"""
<table>
    <thead><tr><th colspan="2">Reschedule Parameters</th></tr></thead>
    <tr><td>Fee Settlement Rebate</td><td>{rp.FeeSettlementRebate}</td></tr>
    <tr><td>Payment Schedule</td><td>{ScheduleConfig.toHtmlTable rp.PaymentSchedule}</td></tr>
    <tr><td>Rate on Negative Balance</td><td>{rp.RateOnNegativeBalance}</td></tr>
    <tr><td>Promotional Interest Rates</td><td>{Array.toStringOrNa rp.PromotionalInterestRates}</td></tr>
    <tr><td>Settlement Day</td><td>{rp.SettlementDay}</td></tr>
</table>"""

    /// merges scheduled payments, determining the currently valid original and rescheduled payments, and preserving a record of any previous payments that have been superseded
    let mergeScheduledPayments (scheduledPayments: (int<OffsetDay> * ScheduledPayment) array) =
        // get a sorted array of all days on which payments are rescheduled
        let rescheduleDays =
            scheduledPayments
            |> Array.map snd
            |> Array.choose (fun sp ->
                if sp.Rescheduled.IsSome then
                    Some sp.Rescheduled.Value.RescheduleDay
                else
                    None
            )
            |> Array.distinct
            |> Array.sort
        // return the list of scheduled payments with the original and rescheduled payments merged
        scheduledPayments
        //group and sort by day
        |> Array.groupBy fst
        |> Array.sortBy fst
        |> Array.mapFold
            (fun previousRescheduleDay (offsetDay, map) ->
                // evaluate the scheduled payment
                let scheduledPayments = map |> Array.map snd
                // get any original payment due on the day
                let original = scheduledPayments |> Array.tryFind _.Original.IsSome |> toValueOption
                // get any rescheduled payments due on the day, ordering them so that the most recently rescheduled payments come first
                let rescheduled =
                    scheduledPayments
                    |> Array.filter _.Rescheduled.IsSome
                    |> Array.sortByDescending _.Rescheduled.Value.RescheduleDay
                    |> Array.toList
                // split any rescheduled payments into latest and previous
                let latestRescheduling, previousReschedulings =
                    match rescheduled with
                    | [ r ] -> ValueSome r, []
                    | r :: pr -> ValueSome r, pr
                    | _ -> ValueNone, []
                // update the previous reschedule day, if any
                let newRescheduleDay =
                    rescheduleDays
                    |> Array.tryFind (fun d -> offsetDay >= d)
                    |> toValueOption
                    |> ValueOption.orElse previousRescheduleDay
                // create the modified scheduled payment
                let newScheduledPayment =
                    match original, latestRescheduling with
                    // if there are any rescheduled payments, add the latest as well as the list of previously rescheduled payments on the day (also include the original if any on the day)
                    | _, ValueSome r ->
                        Some(
                            offsetDay,
                            {
                                Original = original |> ValueOption.bind _.Original
                                Rescheduled = r.Rescheduled
                                PreviousRescheduled =
                                    previousReschedulings
                                    |> List.rev
                                    |> List.map _.Rescheduled.Value
                                    |> List.toArray
                                Adjustment = r.Adjustment
                                Metadata = r.Metadata
                            }
                        )
                    // if there is no rescheduled payment on the day, but just an original payment, include the original payment as-is
                    // note: if the original payment day is preceded by any rescheduling, then assume that this cancels the original payment, so enter this as a zero-valued rescheduled payment on the day
                    | ValueSome o, ValueNone ->
                        Some(
                            offsetDay,
                            {
                                Original = o.Original
                                Rescheduled =
                                    newRescheduleDay
                                    |> ValueOption.bind (fun nrd ->
                                        if offsetDay >= nrd then
                                            //overwrite original scheduled payments from start of rescheduled payments
                                            ValueSome {
                                                Value = 0L<Cent>
                                                RescheduleDay = nrd
                                            }
                                        else
                                            ValueNone
                                    )
                                PreviousRescheduled = [||]
                                Adjustment = o.Adjustment
                                Metadata = o.Metadata
                            }
                        )
                    // if there are no original or rescheduled payments, ignore
                    | ValueNone, ValueNone -> None

                newScheduledPayment, newRescheduleDay
            )
            ValueNone
        |> fst
        |> Array.choose id
        // convert the result to a map
        |> Map.ofArray

    /// take an existing schedule and reschedule the remaining payments e.g. to allow the customer more time to pay
    let reschedule p (rp: RescheduleParameters) actualPayments =

        // get the settlement quote
        let quote = getQuote p actualPayments

        // create a new payment schedule either by auto-generating it or using manual payments
        let newPaymentSchedule =
            match rp.PaymentSchedule with
            | AutoGenerateSchedule _ ->
                calculateBasicSchedule {
                    p.Basic with
                        ScheduleConfig = rp.PaymentSchedule
                }
                |> _.Items
                |> Array.filter (_.ScheduledPayment >> ScheduledPayment.isSome)
                |> Array.map (fun si -> si.Day, si.ScheduledPayment)
            | FixedSchedules fixedSchedules ->
                fixedSchedules
                |> Array.collect (fun fs ->
                    let scheduledPayment =
                        match fs.ScheduleType with
                        | ScheduleType.Original -> ScheduledPayment.quick (ValueSome fs.PaymentValue) ValueNone
                        | ScheduleType.Rescheduled rescheduleDay ->
                            ScheduledPayment.quick
                                ValueNone
                                (ValueSome {
                                    Value = fs.PaymentValue
                                    RescheduleDay = rescheduleDay
                                })

                    UnitPeriod.generatePaymentSchedule
                        (UnitPeriod.PaymentCount fs.PaymentCount)
                        UnitPeriod.Direction.Forward
                        fs.UnitPeriodConfig
                    |> Array.map (fun d -> OffsetDay.fromDate p.Basic.StartDate d, scheduledPayment)
                )
            | CustomSchedule payments -> payments |> Map.toArray

        // append the new schedule to the old schedule up to the point of settlement
        let oldPaymentSchedule =
            quote.Schedules.AmortisationSchedule.ScheduleItems
            |> Map.filter (fun _ si -> ScheduledPayment.isSome si.ScheduledPayment)
            |> Map.map (fun _ si -> si.ScheduledPayment)
            |> Map.toArray

        // configure the parameters for the new schedule
        let pNew = {
            p with
                Basic.ScheduleConfig =
                    [| oldPaymentSchedule; newPaymentSchedule |]
                    |> Array.concat
                    |> mergeScheduledPayments
                    |> CustomSchedule
                Advanced.FeeConfig =
                    p.Advanced.FeeConfig
                    |> ValueOption.map (fun fc -> {
                        fc with
                            SettlementRebate = rp.FeeSettlementRebate
                    })
                Advanced.InterestConfig.InitialGracePeriod = 0<DurationDay>
                Advanced.InterestConfig.PromotionalRates = rp.PromotionalInterestRates
                Advanced.InterestConfig.RateOnNegativeBalance = rp.RateOnNegativeBalance
                Advanced.SettlementDay = rp.SettlementDay
                Advanced.TrimEnd = true
        }

        // create the new amortisation schedule
        let rescheduledSchedules = amortise pNew actualPayments

        // return the results
        {|
            OldSchedules = quote.Schedules
            NewSchedules = rescheduledSchedules
        |}

    /// parameters for creating a rolled-over schedule
    [<RequireQualifiedAccess>]
    type RolloverParameters = {
        /// the final payment day of the original schedule
        OriginalFinalPaymentDay: int<OffsetDay>
        /// the scheduled payments or the parameters for generating them
        PaymentSchedule: ScheduleConfig
        /// options relating to interest
        InterestConfig: Interest.BasicConfig
        /// options relating to payment
        PaymentConfig: Payment.BasicConfig
        /// how to handle any outstanding fee balance
        FeeHandling: Fee.FeeHandling
    }

    /// parameters for creating a rolled-over schedule
    module RolloverParameters =

        /// formats the parameters items as an HTML table
        let toHtmlTable (rp: RolloverParameters) =
            $"""
<table>
    <thead><tr><th colspan="2">Rollover Parameters</th></tr></thead>
    <tr><td>Original Final Payment Day</td><td>{rp.OriginalFinalPaymentDay}</td></tr>
    <tr><td>Payment Schedule</td><td>{ScheduleConfig.toHtmlTable rp.PaymentSchedule}</td></tr>
    <tr><td>Interest Config</td><td>{rp.InterestConfig}</td></tr>
    <tr><td>Payment Config</td><td>{rp.PaymentConfig}</td></tr>
    <tr><td>Fee Handling</td><td>{rp.FeeHandling}</td></tr>
</table>"""

    /// take an existing schedule and settle it, then use the result to create a new schedule to pay it off under different terms
    let rollOver p (rp: RolloverParameters) actualPayments =

        // get the settlement quote
        let quote = getQuote p actualPayments

        // process the quote and extract the portions if applicable
        let principalPortion, feePortion, feeRebateIfSettled =
            match quote.QuoteResult with
            | PaymentQuote({ Apportionment = a } as pq) ->
                match rp.FeeHandling with
                | Fee.FeeHandling.CapitaliseAsPrincipal ->
                    a.PrincipalPortion + a.FeePortion + a.InterestPortion + a.ChargesPortion,
                    0L<Cent>,
                    pq.FeeRebateIfSettled
                | Fee.FeeHandling.CarryOverAsIs ->
                    a.PrincipalPortion + a.InterestPortion + a.ChargesPortion, a.FeePortion, pq.FeeRebateIfSettled
                | Fee.FeeHandling.WriteOffFeeBalance ->
                    a.PrincipalPortion + a.InterestPortion + a.ChargesPortion, a.FeePortion, pq.FeeRebateIfSettled
            | _ -> failwith "Unable to obtain quote for rollover"

        // configure the parameters for the new schedule
        let pNew = {
            p with
                Basic.StartDate = p.Basic.EvaluationDate
                Basic.Principal = principalPortion
                Basic.ScheduleConfig = rp.PaymentSchedule
                Basic.InterestConfig = rp.InterestConfig
                Basic.PaymentConfig = rp.PaymentConfig
                Basic.FeeConfig =
                    p.Basic.FeeConfig
                    |> ValueOption.bind (fun fc ->
                        match rp.FeeHandling with
                        | Fee.FeeHandling.CarryOverAsIs ->
                            {
                                fc with
                                    FeeType = Fee.CustomFee("Rollover Fee", Amount.Simple feePortion)
                            }
                            |> ValueSome
                        | _ -> ValueNone
                    )
                Advanced.FeeConfig =
                    p.Advanced.FeeConfig
                    |> ValueOption.map (fun fc -> {
                        fc with
                            SettlementRebate =
                                if feeRebateIfSettled = 0L<Cent> then
                                    Fee.SettlementRebate.Zero
                                else
                                    match fc.SettlementRebate with
                                    | Fee.SettlementRebate.ProRata
                                    | Fee.SettlementRebate.ProRataRescheduled _ ->
                                        Fee.SettlementRebate.ProRataRescheduled rp.OriginalFinalPaymentDay
                                    | _ as fsr -> fsr
                    })
                Advanced.SettlementDay = SettlementDay.NoSettlement
                Advanced.TrimEnd = true
        }

        // create the new amortisation schedule
        let rolledOverSchedules = amortise pNew Map.empty

        // return the results
        {|
            OldSchedules = quote.Schedules
            NewSchedules = rolledOverSchedules
        |}

    /// parameters for comparing the cost of remaining on the current mortgage product against switching to a new one
    [<RequireQualifiedAccess>]
    type RemortgageComparisonParameters = {
        /// any early repayment charge on the current product, expressed as an amount relative to the outstanding capital balance
        EarlyRepaymentCharge: Amount
        /// any upfront arrangement fee payable on the new product
        ArrangementFee: int64<Cent>
        /// any legal or other upfront costs associated with switching
        LegalCosts: int64<Cent>
        /// the parameters for the new product (the principal should be set to the current outstanding balance)
        NewProductParameters: Parameters
    }

    /// the result of a remortgage cost comparison
    [<Struct>]
    type RemortgageComparisonResult = {
        /// the outstanding capital balance at the point of comparison
        OutstandingBalance: int64<Cent>
        /// the early repayment charge payable if switching
        EarlyRepaymentCharge: int64<Cent>
        /// the total upfront switching costs (ERC + arrangement fee + legal costs)
        UpfrontSwitchCosts: int64<Cent>
        /// the total cost of remaining on the current product for the remaining scheduled term
        StayTotalCost: int64<Cent>
        /// the total cost of switching to the new product, including all upfront costs
        SwitchTotalCost: int64<Cent>
        /// the net benefit of switching (positive = switching saves money, negative = staying is cheaper)
        NetBenefit: int64<Cent>
        /// the number of payment periods after which the cumulative per-period savings recover the upfront switching costs;
        /// ValueNone if the new product is not cheaper per period or break-even is not reached within the remaining term
        BreakEvenPeriodCount: int voption
    }

    /// compares the total cost of remaining on the current mortgage product against switching to a new one,
    /// accounting for any early repayment charges, arrangement fees and legal costs
    let compareRemortgage p actualPayments (rcp: RemortgageComparisonParameters) =

        // get a settlement quote to determine the current outstanding balance
        let quote = getQuote p actualPayments

        // extract the outstanding principal balance from the settlement quote
        let outstandingBalance =
            match quote.QuoteResult with
            | PaymentQuote pq -> pq.Apportionment.PrincipalPortion
            | _ -> failwith "Unable to obtain settlement quote for remortgage comparison"

        // calculate the early repayment charge based on the outstanding capital balance
        let ercAmount =
            Amount.total outstandingBalance rcp.EarlyRepaymentCharge
            |> Cent.fromDecimalCent (RoundWith MidpointRounding.AwayFromZero)

        let upfrontCosts = ercAmount + rcp.ArrangementFee + rcp.LegalCosts

        // "stay" cost: sum of all remaining original scheduled payments after the evaluation day
        let evaluationDay = OffsetDay.fromDate p.Basic.StartDate p.Basic.EvaluationDate

        let stayScheduledPayments =
            quote.Schedules.AmortisationSchedule.ScheduleItems
            |> Map.toArray
            |> Array.filter (fun (day, si) ->
                day > evaluationDay
                && ScheduledPayment.isSome si.ScheduledPayment)
            |> Array.map (fun (_, si) -> ScheduledPayment.total si.ScheduledPayment)

        let stayCost = stayScheduledPayments |> Array.sum
        let stayPaymentCount = stayScheduledPayments.Length

        // "switch" cost: total scheduled payments on the new product plus upfront costs
        let newBasicSchedule = calculateBasicSchedule rcp.NewProductParameters.Basic
        let switchPaymentsTotal = newBasicSchedule.Stats.ScheduledPaymentTotal
        let switchCost = upfrontCosts + switchPaymentsTotal

        let netBenefit = stayCost - switchCost

        // break-even: number of payment periods until cumulative per-period savings exceed the upfront costs
        let switchLevelPayment = newBasicSchedule.Stats.LevelPayment
        let stayAveragePayment =
            if stayPaymentCount > 0 then stayCost / int64 stayPaymentCount
            else 0L<Cent>

        let perPeriodSaving = stayAveragePayment - switchLevelPayment

        let breakEvenPeriodCount =
            if perPeriodSaving <= 0L<Cent> then
                ValueNone
            else
                let periods = int (Math.Ceiling(decimal upfrontCosts / decimal perPeriodSaving))
                if periods <= stayPaymentCount then ValueSome periods
                else ValueNone

        {
            OutstandingBalance = outstandingBalance
            EarlyRepaymentCharge = ercAmount
            UpfrontSwitchCosts = upfrontCosts
            StayTotalCost = stayCost
            SwitchTotalCost = switchCost
            NetBenefit = netBenefit
            BreakEvenPeriodCount = breakEvenPeriodCount
        }

    /// parameters for comparing the cost of paying multiple debts individually against consolidating them into a single facility
    [<RequireQualifiedAccess>]
    type DebtConsolidationParameters = {
        /// the discount rate used to calculate the present value of future cash flows
        /// (typically the opportunity cost of capital or a risk-free rate)
        DiscountRate: Interest.Rate
        /// the parameters for the new consolidated facility
        ConsolidatedFacilityParameters: Parameters
        /// any upfront fees associated with setting up the consolidated facility
        ConsolidationFees: int64<Cent>
    }

    /// the result of a debt consolidation NPV comparison
    [<Struct>]
    type DebtConsolidationResult = {
        /// the net present value of continuing to pay each existing debt individually
        IndividualPaymentsNpv: int64<Cent>
        /// the net present value of replacing all debts with the consolidated facility (including any upfront fees)
        ConsolidatedPaymentsNpv: int64<Cent>
        /// the net saving from consolidation in present-value terms
        /// (positive = consolidation is more economical, negative = paying individually is cheaper)
        NetConsolidationSaving: int64<Cent>
    }

    /// compares the NPV of paying multiple existing debts individually against consolidating them into a single new
    /// facility, using the specified discount rate to reflect the time value of money and the opportunity cost of
    /// extending the overall repayment term
    let compareDebtConsolidation
        (existingDebts: (Parameters * Map<int<OffsetDay>, ActualPayment array>) array)
        (dcp: DebtConsolidationParameters)
        =

        /// days in a year used to convert an annual rate to a daily rate
        let daysPerYear = 365.0

        // compute the daily discount rate from the specified annual or daily rate
        let dailyDiscountRate =
            match dcp.DiscountRate with
            | Interest.Rate.Zero -> 0m
            | Interest.Rate.Annual(Percent air) ->
                decimal (Math.Pow(double (1m + air / 100m), 1.0 / daysPerYear)) - 1m
            | Interest.Rate.Daily(Percent dir) -> dir / 100m

        // the reference date for all NPV calculations is the evaluation date of the consolidated facility
        let referenceDate = dcp.ConsolidatedFacilityParameters.Basic.EvaluationDate

        // NPV of consolidated facility repayments (compute first to collect all unique day counts)
        let consolidatedParams = dcp.ConsolidatedFacilityParameters
        let consolidatedBasicSchedule = calculateBasicSchedule consolidatedParams.Basic
        let consolidatedEvaluationDay =
            OffsetDay.fromDate consolidatedParams.Basic.StartDate consolidatedParams.Basic.EvaluationDate

        // collect (paymentDate, amount) pairs for individual debts
        let individualPaymentPairs =
            existingDebts
            |> Array.collect (fun (p, actualPayments) ->
                let quote = getQuote p actualPayments
                let evaluationDay = OffsetDay.fromDate p.Basic.StartDate p.Basic.EvaluationDate

                quote.Schedules.AmortisationSchedule.ScheduleItems
                |> Map.toArray
                |> Array.choose (fun (day, si) ->
                    if day > evaluationDay && ScheduledPayment.isSome si.ScheduledPayment then
                        let payment = ScheduledPayment.total si.ScheduledPayment
                        let paymentDate = OffsetDay.toDate p.Basic.StartDate day
                        let daysFromRef = max 0 (paymentDate - referenceDate).Days
                        Some(daysFromRef, payment)
                    else
                        None
                )
            )

        // collect (daysFromRef, amount) pairs for consolidated facility
        let consolidatedPaymentPairs =
            consolidatedBasicSchedule.Items
            |> Array.choose (fun item ->
                if item.Day > consolidatedEvaluationDay && ScheduledPayment.isSome item.ScheduledPayment then
                    let payment = ScheduledPayment.total item.ScheduledPayment
                    let paymentDate = OffsetDay.toDate consolidatedParams.Basic.StartDate item.Day
                    let daysFromRef = max 0 (paymentDate - referenceDate).Days
                    Some(daysFromRef, payment)
                else
                    None
            )

        // build a memoised discount-factor lookup for all unique day counts across both strategies
        let discountFactorCache =
            if dailyDiscountRate = 0m then
                Map.empty
            else
                [| individualPaymentPairs; consolidatedPaymentPairs |]
                |> Array.concat
                |> Array.map fst
                |> Array.distinct
                |> Array.map (fun days ->
                    let factor =
                        if days <= 0 then 1m
                        else 1m / decimal (Math.Pow(double (1m + dailyDiscountRate), double days))
                    days, factor
                )
                |> Map.ofArray

        // look up a discount factor, defaulting to 1 when the rate is zero
        let discountFactor days =
            discountFactorCache |> Map.tryFind days |> Option.defaultValue 1m

        // NPV of all individual debt repayments
        let individualNpv =
            individualPaymentPairs
            |> Array.sumBy (fun (daysFromRef, payment) ->
                Cent.toDecimalCent payment * discountFactor daysFromRef
            )

        // NPV of consolidated facility repayments
        let consolidatedPaymentsNpv =
            consolidatedPaymentPairs
            |> Array.sumBy (fun (daysFromRef, payment) ->
                Cent.toDecimalCent payment * discountFactor daysFromRef
            )

        // add any upfront consolidation fees (paid immediately at reference date, discount factor = 1)
        let consolidatedTotalNpv =
            consolidatedPaymentsNpv + Cent.toDecimalCent dcp.ConsolidationFees

        let netSaving = individualNpv - consolidatedTotalNpv

        {
            IndividualPaymentsNpv = Cent.fromDecimalCent (RoundWith MidpointRounding.AwayFromZero) individualNpv
            ConsolidatedPaymentsNpv = Cent.fromDecimalCent (RoundWith MidpointRounding.AwayFromZero) consolidatedTotalNpv
            NetConsolidationSaving = Cent.fromDecimalCent (RoundWith MidpointRounding.AwayFromZero) netSaving
        }
